server.port=8080
spring.application.name=api-redirector
logging.level.org.springframework=INFO
logging.level.com.supracor.redirector=DEBUG
spring.web.cors.allowed-origin-patterns=http://supracor.co.id
spring.web.cors.allow-credentials=true